// Mock data for the dashboard — swap with real API calls later

export const dashboardSummary = {
  org_id: "org_greenledger_demo",
  total_inferences: 1_247,
  total_co2e_g: 342.8,
  total_energy_wh: 891.4,
  total_water_ml: 1_245.6,
  total_levy_usd: 0.68,
  total_carbon_removed_g: 280.5,
  avg_savings_vs_naive_pct: 62.3,
  sustainability_score: 78,
  active_agents: 8,
  period_start: "2026-03-01",
  period_end: "2026-03-31",
};

export const orgScore = {
  current_score: 78,
  previous_score: 71,
  change: 7,
  components: {
    carbon_efficiency: 82,
    budget_adherence: 90,
    offset_coverage: 65,
    optimization_adoption: 72,
    trend: 81,
  },
  recommendations: [
    {
      id: "rec_1",
      org_id: "org_demo",
      scope: "org" as const,
      scope_id: "org_demo",
      title: "Switch simple queries to Haiku 4.5",
      description:
        "38% of your queries classified as 'simple' are using Sonnet. Downgrading these to Haiku would save ~45g CO2e/month with negligible quality loss.",
      estimated_savings_co2e_g: 45,
      estimated_savings_pct: 13,
      priority: "high",
      created_at: "2026-03-28",
    },
    {
      id: "rec_2",
      org_id: "org_demo",
      scope: "org" as const,
      scope_id: "org_demo",
      title: "Schedule batch jobs during low-carbon hours",
      description:
        "Your nightly batch processing runs at 2am UTC when grid carbon intensity averages 420 gCO2e/kWh. Moving to 6am UTC would reduce intensity to ~180 gCO2e/kWh.",
      estimated_savings_co2e_g: 28,
      estimated_savings_pct: 8,
      priority: "medium",
      created_at: "2026-03-28",
    },
    {
      id: "rec_3",
      org_id: "org_demo",
      scope: "org" as const,
      scope_id: "org_demo",
      title: "Enable carbon wallet for research-agent-3",
      description:
        "This agent has no budget cap and accounts for 22% of your total emissions. Setting a budget would enforce accountability.",
      estimated_savings_co2e_g: 15,
      estimated_savings_pct: 4,
      priority: "low",
      created_at: "2026-03-28",
    },
  ],
};

export const emissionsOverTime = [
  { date: "Mar 1", co2e: 8.2, energy: 22.1 },
  { date: "Mar 5", co2e: 12.4, energy: 31.5 },
  { date: "Mar 9", co2e: 9.8, energy: 25.9 },
  { date: "Mar 13", co2e: 15.1, energy: 38.2 },
  { date: "Mar 17", co2e: 11.3, energy: 29.0 },
  { date: "Mar 21", co2e: 13.7, energy: 35.4 },
  { date: "Mar 25", co2e: 10.5, energy: 27.8 },
  { date: "Mar 29", co2e: 8.9, energy: 23.6 },
];

export const modelUsage = [
  { name: "Haiku 4.5", value: 482, color: "#22c55e" },
  { name: "Sonnet 4.6", value: 389, color: "#3b82f6" },
  { name: "GPT-4.1 Mini", value: 198, color: "#a855f7" },
  { name: "Gemini Flash", value: 112, color: "#f59e0b" },
  { name: "Opus 4.6", value: 42, color: "#ef4444" },
  { name: "o3-mini", value: 24, color: "#ec4899" },
];

export const agentScores = [
  {
    agent_id: "procurement-agent-1",
    display_name: "Procurement Agent",
    total_inferences: 312,
    total_co2e_g: 48.2,
    total_energy_wh: 128.4,
    wallet_utilization_pct: 64,
    sustainability_score: 88,
    trend: "on_track" as const,
  },
  {
    agent_id: "research-agent-2",
    display_name: "Research Agent",
    total_inferences: 287,
    total_co2e_g: 92.1,
    total_energy_wh: 245.8,
    wallet_utilization_pct: 78,
    sustainability_score: 72,
    trend: "on_track" as const,
  },
  {
    agent_id: "research-agent-3",
    display_name: "Deep Research Agent",
    total_inferences: 156,
    total_co2e_g: 124.5,
    total_energy_wh: 312.1,
    wallet_utilization_pct: null,
    sustainability_score: 45,
    trend: "at_risk" as const,
  },
  {
    agent_id: "support-agent-4",
    display_name: "Customer Support Bot",
    total_inferences: 492,
    total_co2e_g: 28.9,
    total_energy_wh: 75.3,
    wallet_utilization_pct: 32,
    sustainability_score: 94,
    trend: "on_track" as const,
  },
];

// --- Green Router ---

export const routingDecisions = [
  {
    id: "route_001",
    timestamp: "2026-03-31T14:32:00Z",
    prompt_preview: "Translate 'hello' to Spanish",
    task_complexity: "simple",
    user_selected: {
      model: "claude-sonnet-4-6",
      provider: "anthropic",
      tier: "standard",
      energy_wh: 0.24,
      co2e_g: 0.096,
    },
    recommended: {
      model: "claude-haiku-4-5",
      provider: "anthropic",
      tier: "light",
      energy_wh: 0.02,
      co2e_g: 0.008,
    },
    alternatives: [
      { model: "gpt-4.1-nano", provider: "openai", tier: "nano", energy_wh: 0.01, co2e_g: 0.004, eco_score: 0.91 },
      { model: "claude-haiku-4-5", provider: "anthropic", tier: "light", energy_wh: 0.02, co2e_g: 0.008, eco_score: 0.89 },
      { model: "gemini-3.1-flash", provider: "google", tier: "light", energy_wh: 0.018, co2e_g: 0.007, eco_score: 0.88 },
      { model: "gpt-4.1-mini", provider: "openai", tier: "light", energy_wh: 0.015, co2e_g: 0.006, eco_score: 0.86 },
      { model: "claude-sonnet-4-6", provider: "anthropic", tier: "standard", energy_wh: 0.24, co2e_g: 0.096, eco_score: 0.82 },
    ],
    assessment: "overkill",
    savings_if_switched_pct: 92,
    accepted_recommendation: true,
    final_model: "claude-haiku-4-5",
  },
  {
    id: "route_002",
    timestamp: "2026-03-31T14:28:00Z",
    prompt_preview: "Write a Python web scraper with error handling and retry logic",
    task_complexity: "complex",
    user_selected: {
      model: "claude-sonnet-4-6",
      provider: "anthropic",
      tier: "standard",
      energy_wh: 0.24,
      co2e_g: 0.096,
    },
    recommended: {
      model: "claude-sonnet-4-6",
      provider: "anthropic",
      tier: "standard",
      energy_wh: 0.24,
      co2e_g: 0.096,
    },
    alternatives: [
      { model: "claude-sonnet-4-6", provider: "anthropic", tier: "standard", energy_wh: 0.24, co2e_g: 0.096, eco_score: 0.82 },
      { model: "gpt-5.2-mini", provider: "openai", tier: "standard", energy_wh: 0.30, co2e_g: 0.12, eco_score: 0.81 },
      { model: "gemini-3.1-pro", provider: "google", tier: "standard", energy_wh: 0.28, co2e_g: 0.11, eco_score: 0.83 },
    ],
    assessment: "appropriate",
    savings_if_switched_pct: 0,
    accepted_recommendation: true,
    final_model: "claude-sonnet-4-6",
  },
  {
    id: "route_003",
    timestamp: "2026-03-31T14:15:00Z",
    prompt_preview: "Prove that the square root of 2 is irrational using proof by contradiction",
    task_complexity: "reasoning",
    user_selected: {
      model: "claude-haiku-4-5",
      provider: "anthropic",
      tier: "light",
      energy_wh: 0.02,
      co2e_g: 0.008,
    },
    recommended: {
      model: "claude-opus-4-6",
      provider: "anthropic",
      tier: "heavy",
      energy_wh: 1.0,
      co2e_g: 0.4,
    },
    alternatives: [
      { model: "o3-mini", provider: "openai", tier: "reasoning", energy_wh: 3.0, co2e_g: 1.2, eco_score: 0.88 },
      { model: "claude-opus-4-6", provider: "anthropic", tier: "heavy", energy_wh: 1.0, co2e_g: 0.4, eco_score: 0.72 },
      { model: "gpt-5.2", provider: "openai", tier: "heavy", energy_wh: 0.55, co2e_g: 0.22, eco_score: 0.77 },
    ],
    assessment: "underpowered",
    savings_if_switched_pct: -4900,
    accepted_recommendation: true,
    final_model: "claude-opus-4-6",
  },
  {
    id: "route_004",
    timestamp: "2026-03-31T13:58:00Z",
    prompt_preview: "What is 2 + 2?",
    task_complexity: "simple",
    user_selected: {
      model: "claude-opus-4-6",
      provider: "anthropic",
      tier: "heavy",
      energy_wh: 1.0,
      co2e_g: 0.4,
    },
    recommended: {
      model: "gpt-4.1-nano",
      provider: "openai",
      tier: "nano",
      energy_wh: 0.01,
      co2e_g: 0.004,
    },
    alternatives: [
      { model: "gpt-4.1-nano", provider: "openai", tier: "nano", energy_wh: 0.01, co2e_g: 0.004, eco_score: 0.91 },
      { model: "claude-haiku-4-5", provider: "anthropic", tier: "light", energy_wh: 0.02, co2e_g: 0.008, eco_score: 0.89 },
    ],
    assessment: "overkill",
    savings_if_switched_pct: 99,
    accepted_recommendation: false,
    final_model: "claude-opus-4-6",
  },
];

// --- Carbon Wallets ---

export const wallets = [
  {
    id: "wallet_001",
    agent_id: "procurement-agent-1",
    display_name: "Procurement Agent",
    monthly_budget_co2e_g: 100,
    current_spend_co2e_g: 48.2,
    on_exceeded: "downgrade_model" as const,
    period_start: "2026-03-01",
    period_end: "2026-03-31",
    trend: "on_track" as const,
    transactions: [
      { date: "Mar 1", spend: 2.1 },
      { date: "Mar 5", spend: 8.4 },
      { date: "Mar 9", spend: 14.2 },
      { date: "Mar 13", spend: 22.5 },
      { date: "Mar 17", spend: 28.9 },
      { date: "Mar 21", spend: 35.1 },
      { date: "Mar 25", spend: 41.8 },
      { date: "Mar 29", spend: 48.2 },
    ],
  },
  {
    id: "wallet_002",
    agent_id: "research-agent-2",
    display_name: "Research Agent",
    monthly_budget_co2e_g: 150,
    current_spend_co2e_g: 92.1,
    on_exceeded: "offset" as const,
    period_start: "2026-03-01",
    period_end: "2026-03-31",
    trend: "on_track" as const,
    transactions: [
      { date: "Mar 1", spend: 5.2 },
      { date: "Mar 5", spend: 18.9 },
      { date: "Mar 9", spend: 32.4 },
      { date: "Mar 13", spend: 48.1 },
      { date: "Mar 17", spend: 58.7 },
      { date: "Mar 21", spend: 71.3 },
      { date: "Mar 25", spend: 82.5 },
      { date: "Mar 29", spend: 92.1 },
    ],
  },
  {
    id: "wallet_003",
    agent_id: "research-agent-3",
    display_name: "Deep Research Agent",
    monthly_budget_co2e_g: 200,
    current_spend_co2e_g: 178.5,
    on_exceeded: "block" as const,
    period_start: "2026-03-01",
    period_end: "2026-03-31",
    trend: "exceeded" as const,
    transactions: [
      { date: "Mar 1", spend: 12.4 },
      { date: "Mar 5", spend: 38.2 },
      { date: "Mar 9", spend: 64.8 },
      { date: "Mar 13", spend: 92.1 },
      { date: "Mar 17", spend: 118.5 },
      { date: "Mar 21", spend: 142.3 },
      { date: "Mar 25", spend: 162.8 },
      { date: "Mar 29", spend: 178.5 },
    ],
  },
  {
    id: "wallet_004",
    agent_id: "support-agent-4",
    display_name: "Customer Support Bot",
    monthly_budget_co2e_g: 80,
    current_spend_co2e_g: 28.9,
    on_exceeded: "defer" as const,
    period_start: "2026-03-01",
    period_end: "2026-03-31",
    trend: "on_track" as const,
    transactions: [
      { date: "Mar 1", spend: 1.8 },
      { date: "Mar 5", spend: 5.2 },
      { date: "Mar 9", spend: 9.1 },
      { date: "Mar 13", spend: 13.4 },
      { date: "Mar 17", spend: 17.2 },
      { date: "Mar 21", spend: 21.5 },
      { date: "Mar 25", spend: 25.1 },
      { date: "Mar 29", spend: 28.9 },
    ],
  },
];

// --- Levy Tracking ---

export const levySummary = {
  total_levy_usd: 0.68,
  total_carbon_removed_g: 280.5,
  total_transactions: 1_247,
  confirmed_pct: 72,
  pooled_pct: 24,
  pending_pct: 4,
  destinations: [
    { name: "Stripe Climate — Frontier", amount_usd: 0.49, carbon_removed_g: 201.2, status: "confirmed" as const },
    { name: "Stripe Climate — Pooled", amount_usd: 0.16, carbon_removed_g: 0, status: "pooled" as const },
    { name: "Pending Settlement", amount_usd: 0.03, carbon_removed_g: 0, status: "pending" as const },
  ],
};

export const levyOverTime = [
  { date: "Mar 1", levy: 0.018, removed: 7.4 },
  { date: "Mar 5", levy: 0.042, removed: 17.2 },
  { date: "Mar 9", levy: 0.031, removed: 12.8 },
  { date: "Mar 13", levy: 0.058, removed: 23.8 },
  { date: "Mar 17", levy: 0.039, removed: 16.0 },
  { date: "Mar 21", levy: 0.048, removed: 19.7 },
  { date: "Mar 25", levy: 0.035, removed: 14.4 },
  { date: "Mar 29", levy: 0.029, removed: 11.9 },
];

export const levyTransactions = [
  { id: "levy_001", timestamp: "2026-03-31T14:32:00Z", agent_id: "procurement-agent-1", amount_usd: 0.00002, co2e_g: 0.012, destination: "Stripe Climate — Frontier", status: "confirmed" as const },
  { id: "levy_002", timestamp: "2026-03-31T14:28:00Z", agent_id: "research-agent-2", amount_usd: 0.00036, co2e_g: 0.18, destination: "Stripe Climate — Frontier", status: "confirmed" as const },
  { id: "levy_003", timestamp: "2026-03-31T14:15:00Z", agent_id: "research-agent-3", amount_usd: 0.0084, co2e_g: 4.2, destination: "Stripe Climate — Pooled", status: "pooled" as const },
  { id: "levy_004", timestamp: "2026-03-31T13:58:00Z", agent_id: "support-agent-4", amount_usd: 0.00001, co2e_g: 0.005, destination: "Stripe Climate — Frontier", status: "confirmed" as const },
  { id: "levy_005", timestamp: "2026-03-31T13:45:00Z", agent_id: "procurement-agent-1", amount_usd: 0.00018, co2e_g: 0.09, destination: "Stripe Climate — Frontier", status: "confirmed" as const },
  { id: "levy_006", timestamp: "2026-03-30T16:20:00Z", agent_id: "research-agent-3", amount_usd: 0.0062, co2e_g: 3.1, destination: "Pending Settlement", status: "pending" as const },
];

// --- Receipts ---

export const recentReceipts = [
  {
    id: "rcpt_001",
    timestamp: "2026-03-31T14:32:00Z",
    agent_id: "procurement-agent-1",
    model: "claude-haiku-4-5",
    provider: "anthropic" as const,
    tokens_in: 245,
    tokens_out: 180,
    environmental_cost: { co2e_g: 0.012, water_ml: 0.04, energy_wh: 0.04 },
    offset: { levy_usd: 0.00002, status: "confirmed" as const, destination: "stripe_climate" },
    comparison: { naive_co2e_g: 0.08, savings_pct: 85 },
  },
  {
    id: "rcpt_002",
    timestamp: "2026-03-31T14:28:00Z",
    agent_id: "research-agent-2",
    model: "claude-sonnet-4-6",
    provider: "anthropic" as const,
    tokens_in: 1_200,
    tokens_out: 890,
    environmental_cost: { co2e_g: 0.18, water_ml: 0.52, energy_wh: 0.48 },
    offset: { levy_usd: 0.00036, status: "confirmed" as const, destination: "stripe_climate" },
    comparison: { naive_co2e_g: 0.72, savings_pct: 75 },
  },
  {
    id: "rcpt_003",
    timestamp: "2026-03-31T14:15:00Z",
    agent_id: "research-agent-3",
    model: "claude-opus-4-6",
    provider: "anthropic" as const,
    tokens_in: 2_400,
    tokens_out: 1_800,
    environmental_cost: { co2e_g: 4.2, water_ml: 12.1, energy_wh: 11.2 },
    offset: { levy_usd: 0.0084, status: "pooled" as const, destination: "stripe_climate" },
    comparison: { naive_co2e_g: 4.2, savings_pct: 0 },
  },
  {
    id: "rcpt_004",
    timestamp: "2026-03-31T13:58:00Z",
    agent_id: "support-agent-4",
    model: "gpt-4.1-nano",
    provider: "openai" as const,
    tokens_in: 120,
    tokens_out: 95,
    environmental_cost: { co2e_g: 0.005, water_ml: 0.01, energy_wh: 0.01 },
    offset: { levy_usd: 0.00001, status: "confirmed" as const, destination: "stripe_climate" },
    comparison: { naive_co2e_g: 0.08, savings_pct: 94 },
  },
  {
    id: "rcpt_005",
    timestamp: "2026-03-31T13:45:00Z",
    agent_id: "procurement-agent-1",
    model: "gemini-3.1-flash",
    provider: "google" as const,
    tokens_in: 800,
    tokens_out: 420,
    environmental_cost: { co2e_g: 0.09, water_ml: 0.28, energy_wh: 0.22 },
    offset: { levy_usd: 0.00018, status: "confirmed" as const, destination: "stripe_climate" },
    comparison: { naive_co2e_g: 0.35, savings_pct: 74 },
  },
];
